name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git diff
        run: |
          echo "获取已修改文件的列表..."
          echo $GITHUB_SHA
          echo $GITHUB_BASE_REF
          echo $GITHUB_HEAD_REF
          # 获取前一个提交的SHA
          PREVIOUS_COMMIT=$(git rev-parse HEAD~1)
          # 获取当前提交的SHA
          CURRENT_COMMIT=$GITHUB_SHA
          # 获取差异
          MODIFIED_FILES=$(git diff  $PREVIOUS_COMMIT $CURRENT_COMMIT)
          echo "$MODIFIED_FILES"
          echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
